#
# Projekt: proj5.tex
# Autor: Dias Assatulla
# Datum: 22.04.2022
# Email: xassat00@fit.vutbr.cz
#
SHELL = /usr/bin/env bash
NAME = proj5
LOGIN = xassat00
IMAGES_DIRECTORY=./bubleImg

all:
	pdflatex $(NAME).tex
	pdflatex $(NAME).tex

clean:
	rm -f *.aux *.log *.nav *.toc *.snm *.out *.vrb

cleanall: clean
	rm -f *.pdf
